=== lavoisier-io/lavoisier.io/lavoisier-xml/src/main/resources/channel.xsd
<!--
  ~ Copyright (C) 2016 Lavoisier.io
  ~
  ~ This file is part of the Lavoisier.io project.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.lavoisier.io" xmlns="http://www.lavoisier.io">

    <xs:element name="channel">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>
                    A channel is the basic building block of Lavoisier. It represents how Lavoisier connects to
                    various applications, web services, and iot objects.
                </xs:documentation>
            </xs:annotation>
            <xs:sequence>
                <xs:element name="id" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            ID of the Channel. Must be unique among all existing channels. You should use a
                            java package like identifier.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="name" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Name of the Channel.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="description" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Short description of the Channel.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="version" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Version number of this channel
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="globalActivationParameters" type="parameters">
                    <xs:annotation>
                        <xs:documentation>
                            List of parameters required for channel global activation. After its global
                            activation, the channel will be available for users activation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="userActivationParameters" type="parameters">
                    <xs:annotation>
                        <xs:documentation>
                            List of parameters required for channel user activation. After its user
                            activation, the channel will be available for use in reactions.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="sparks" type="sparks">
                    <xs:annotation>
                        <xs:documentation>
                            The list of sparks exposed by this channel. A spark is an external event triggering a
                            reaction.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="conditions" type="conditions">
                    <xs:annotation>
                        <xs:documentation>
                            The list of conditions exposed by this channel. A condition must be met for a reaction to
                            happen.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="fuels" type="fuels">
                    <xs:annotation>
                        <xs:documentation>
                            Fuel is data used by a reaction to produce an action.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="actions" type="actions">
                    <xs:annotation>
                        <xs:documentation>
                            The list of actions exposed by this channel. The actions will be executed when spark happens
                            and if conditions are met.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="spark">
        <xs:annotation>
            <xs:documentation>
                A spark is an external event triggering a reaction.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="id" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        ID of the spark. It should be unique among all channel's sparks.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="name" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Name of the spark
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Description of the spark
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="input" type="parameters">
                <xs:annotation>
                    <xs:documentation>
                        Input parameters required for this spark to be triggered.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="output" type="variables">
                <xs:annotation>
                    <xs:documentation>
                        Output data variables produced by this spark.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sparks">
        <xs:sequence>
            <xs:element name="spark" type="spark" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="condition">
        <xs:annotation>
            <xs:documentation>
                A condition must be met for a reaction to happen.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="id" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        ID of the condition. It should be unique among all channel's conditions.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="name" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Name of the condition
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Description of the condition
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="input" type="parameters">
                <xs:annotation>
                    <xs:documentation>
                        Input parameters of the condition.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="conditions">
        <xs:sequence>
            <xs:element name="condition" type="condition" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fuel">
        <xs:annotation>
            <xs:documentation>
                Fuel is data used by a reaction to produce an action.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="id" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        ID of the fuel. It should be unique among all channel's sparks.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="name" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Name of the fuel
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Description of the fuel
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="input" type="parameters">
                <xs:annotation>
                    <xs:documentation>
                        Input parameters of the fuel.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="output" type="variables">
                <xs:annotation>
                    <xs:documentation>
                        Output data variables produced by this fuel.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fuels">
        <xs:sequence>
            <xs:element name="fuel" type="fuel" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="action">
        <xs:annotation>
            <xs:documentation>
                An action is something to be done in reaction to a trigger when conditions are met.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="id" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        ID of the Action. It should be unique among all channel's actions.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="name" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Name of the Action
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Description of the Action.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="input" type="parameters">
                <xs:annotation>
                    <xs:documentation>
                        Input parameters required for this action execution.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="actions">
        <xs:sequence>
            <xs:element name="action" type="action" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameter">
        <xs:attribute name="key" type="xs:string" use="required" />
        <xs:attribute name="type" type="parameterType" use="required" />
    </xs:complexType>

    <xs:complexType name="parameters">
        <xs:sequence>
            <xs:element name="parameter" type="parameter"  minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="variable">
        <xs:attribute name="key" type="xs:string" use="required" />
        <xs:attribute name="type" type="parameterType" use="required" />
    </xs:complexType>

    <xs:complexType name="variables">
        <xs:sequence>
            <xs:element name="variable" type="variable" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="parameterType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string" />
            <xs:enumeration value="text" />
            <xs:enumeration value="date" />
            <xs:enumeration value="number" />
            <xs:enumeration value="file" />
            <xs:enumeration value="image-file" />
            <xs:enumeration value="url" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== lavoisier-io/lavoisier.io/lavoisier-xml/src/test/resources/exemple-channel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016 Lavoisier.io
  ~
  ~ This file is part of the Lavoisier.io project.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<channel xmlns="http://www.lavoisier.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lavoisier.io channel.xsd">
    <name>channel.twitter.name</name>
    <description>channel.twitter.description</description>
    <version>1.1.0</version>
    <globalActivationParameters>
        <parameter key="channel.twitter.global-activation.app-id" type="string"/>
        <parameter key="channel.twitter.global-activation.app-secret" type="number"/>
    </globalActivationParameters>
    <userActivationParameters>
        <parameter key="channel.twitter.user-activation.token" type="date"/>
    </userActivationParameters>
    <triggers>
        <trigger>
            <name>channel.twitter.trigger.mention.name</name>
            <description>channel.twitter.trigger.mention.description</description>
            <input>
            </input>
            <output>
                <variable key="channel.twitter.trigger.mention.output.tweet-content" type="text"/>
                <variable key="channel.twitter.trigger.mention.output.tweet-author" type="string"/>
                <variable key="channel.twitter.trigger.mention.output.tweet-url" type="url"/>
                <variable key="channel.twitter.trigger.mention.output.tweet-date" type="date"/>
            </output>
        </trigger>
        <trigger>
            <name>channel.twitter.trigger.newtweet.name</name>
            <description>channel.twitter.trigger.newtweet.description</description>
            <input>
                <parameter key="channel.twitter.trigger.newtweet.input.tweet-author" type="string"/>
            </input>
            <output>
                <variable key="channel.twitter.trigger.newtweet.output.tweet-content" type="text"/>
                <variable key="channel.twitter.trigger.newtweet.output.tweet-author" type="string"/>
                <variable key="channel.twitter.trigger.newtweet.output.tweet-url" type="url"/>
                <variable key="channel.twitter.trigger.newtweet.output.tweet-date" type="date"/>
            </output>
        </trigger>
    </triggers>
    <actions>
        <action>
            <name>channel.twitter.action.posttweet.name</name>
            <description>channel.twitter.action.posttweet.description</description>
            <input>
                <parameter key="channel.twitter.action.posttweet.input.tweet-content" type="text"/>
            </input>
        </action>
    </actions>
</channel>
